#Vehicles Attributes.
#TunerStudio by Philip Tobin
#Sun Jun 21 15:53:52 PDT 2026
converterStall=
injectorSize=440
firstGearRatio=
fourthGearRatio=
finalDriveRatio=
transmissionType=Manual
fifthGearRatio=
weight=
thirdGearRatio=
sixthGearRatio=
secondGearRatio=
engineDisplacement=1839
